import { createHash } from "node:crypto";
import { access, mkdir, open, readFile, readdir, rename, stat } from "node:fs/promises";
import path from "node:path";
import type { Pool, PoolClient } from "pg";

export const DOC_KINDS = ["guide", "setting", "proposal", "dev", "next"] as const;
export const TASK_STATUSES = ["pending", "in-progress", "done", "failed"] as const;
export type DocKind = (typeof DOC_KINDS)[number];
export type TaskStatus = (typeof TASK_STATUSES)[number];
export type Frontmatter = { title: string; project: string; user: string; "pre-task": string | null; "next-task": string | null; type: "task" | "report"; created_at: string; timeout_min?: number; [key: string]: string | number | null | undefined };

const slugPattern = /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/;
export function assertSlug(value: string) { if (value.length < 2 || !slugPattern.test(value)) throw new Error("invalid_slug"); return value; }
export function slugify(value: string) { const slug = value.normalize("NFKD").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 63).replace(/-$/, ""); return slug.length >= 2 ? slug : `p-${slug || "project"}`; }
export function dataRoot() { return path.resolve(process.env.APMS_DATA_ROOT || "./data"); }
function withinRoot(...segments: string[]) { segments.forEach(assertSlug); const root = dataRoot(); const value = path.resolve(root, ...segments); if (value !== root && !value.startsWith(`${root}${path.sep}`)) throw new Error("path_escape"); return value; }
export function projectRoot(user: string, project: string) { return withinRoot(user, project); }
export function docPath(user: string, project: string, kind: DocKind) { if (!DOC_KINDS.includes(kind)) throw new Error("invalid_doc_kind"); return path.join(projectRoot(user, project), "docs", `${project}.${kind}.md`); }
export function taskPath(user: string, project: string, status: TaskStatus | "reports", filename: string) { if (![...TASK_STATUSES, "reports"].includes(status)) throw new Error("invalid_status"); if (!/^\d{8}-\d{3}-(?:task|report)\.md$/.test(filename)) throw new Error("invalid_filename"); return path.join(projectRoot(user, project), "tasks", status, filename); }

const templates: Record<DocKind, (name: string) => string> = {
  guide: (name) => `# ${name} 프로젝트 지침\n\n## 프로젝트 목적\n\n## 기술 스택과 구조\n\n## 작업 규칙\n\n## 보안과 금지사항\n\n## 테스트와 검증\n\n- [ ] 필수 테스트 통과\n- [ ] 변경 범위 확인\n\n## 배포 규칙\n\n## 완료 정의\n`,
  setting: (name) => `# ${name} 설정\n`, proposal: (name) => `# ${name} 기획서\n`, dev: (name) => `# ${name} 개발 현황\n`, next: (name) => `# ${name} 핸드오버\n\n## 현재 목표\n\n## 확정 결정\n\n## 최근 작업\n\n## 열린 질문\n\n## 다음 행동\n`,
};
async function atomicWrite(file: string, content: string, exclusive = false) { await mkdir(path.dirname(file), { recursive: true }); const temp = `${file}.${process.pid}.${Date.now()}.tmp`; const handle = await open(temp, exclusive ? "wx" : "w"); try { await handle.writeFile(content, "utf8"); await handle.sync(); } finally { await handle.close(); } try { if (exclusive) await access(file).then(() => { throw new Error("file_exists"); }).catch((error: NodeJS.ErrnoException) => { if (error.code !== "ENOENT") throw error; }); await rename(temp, file); } catch (error) { throw error; } }
export async function initializeProject(user: string, project: string, name: string) { const root = projectRoot(user, project); await mkdir(path.join(root, "docs"), { recursive: true }); await mkdir(path.join(dataRoot(), user, "docs"), { recursive: true }); await Promise.all([...TASK_STATUSES, "reports"].map((s) => mkdir(path.join(root, "tasks", s), { recursive: true }))); await Promise.all(DOC_KINDS.map(async (kind) => { const file = docPath(user, project, kind); try { await atomicWrite(file, templates[kind](name), true); } catch (e) { if (!(e instanceof Error) || e.message !== "file_exists") throw e; } })); return root; }
export async function readDocument(user: string, project: string, kind: DocKind) { return readFile(docPath(user, project, kind), "utf8"); }
export async function documentMetadata(user: string, project: string, kind: DocKind) { const file=docPath(user,project,kind);const [content,info]=await Promise.all([readFile(file,"utf8"),stat(file)]);return{content,etag:`"${contentHash(content)}"`,updatedAt:info.mtime.toISOString()}; }
export async function writeDocument(user: string, project: string, kind: DocKind, content: string) { await atomicWrite(docPath(user, project, kind), content); }

function yamlValue(value: string | number | null | undefined) { if (value == null) return "null"; if (typeof value === "number") return String(value); return JSON.stringify(value); }
export function serializeMarkdown(frontmatter: Frontmatter, body: string) { const required = ["title", "project", "user", "pre-task", "next-task", "type", "created_at", ...(frontmatter.type === "task" ? ["timeout_min"] : [])]; const extras = Object.keys(frontmatter).filter((k) => !required.includes(k)); return `---\n${[...required, ...extras].map((k) => `${k}: ${yamlValue(frontmatter[k])}`).join("\n")}\n---\n\n${body.replace(/^\s+/, "").replace(/\s*$/, "")}\n`; }
export function parseMarkdown(source: string) { const match = source.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/); if (!match) throw new Error("invalid_frontmatter"); const frontmatter: Record<string, string | number | null> = {}; for (const line of match[1].split(/\r?\n/)) { const m = line.match(/^([a-z_-]+):\s*(.*)$/); if (!m || m[1] in frontmatter || /[&*!][A-Za-z]/.test(m[2])) throw new Error("invalid_frontmatter"); let value: string | number | null = m[2]; if (value === "null") value = null; else if (/^-?\d+$/.test(value)) value = Number(value); else if (value.startsWith('"')) value = JSON.parse(value); frontmatter[m[1]] = value; } return { frontmatter: frontmatter as Frontmatter, body: match[2].replace(/^\r?\n/, "").replace(/\s+$/, "") }; }
export function contentHash(value: string) { return createHash("sha256").update(value).digest("hex"); }
export async function nextTaskFilename(user: string, project: string, now = new Date()) { const day = now.toISOString().slice(0, 10).replace(/-/g, ""); let max = 0; for (const status of [...TASK_STATUSES, "reports"] as const) { const dir = path.join(projectRoot(user, project), "tasks", status); for (const file of await readdir(dir).catch(() => [])) { const m = file.match(new RegExp(`^${day}-(\\d{3})-(?:task|report)\\.md$`)); if (m) max = Math.max(max, Number(m[1])); } } if (max >= 999) throw new Error("sequence_exhausted"); return `${day}-${String(max + 1).padStart(3, "0")}-task.md`; }
export async function createTaskFile(user: string, project: string, frontmatter: Frontmatter, body: string, now = new Date()) { const filename = await nextTaskFilename(user, project, now); const content = serializeMarkdown(frontmatter, body); await atomicWrite(taskPath(user, project, "pending", filename), content, true); return { filename, content, path: taskPath(user, project, "pending", filename) }; }
export async function moveTask(user: string, project: string, filename: string, from: TaskStatus, to: TaskStatus, dbClient: Pick<PoolClient, "query">, projectId: string) { const source = taskPath(user, project, from, filename); const target = taskPath(user, project, to, filename); await access(target).then(() => { throw new Error("target_exists"); }).catch((e: NodeJS.ErrnoException) => { if (e.code !== "ENOENT") throw e; }); await rename(source, target); await dbClient.query("UPDATE tasks SET status=$1, file_path=$2, updated_at=now() WHERE project_id=$3 AND filename=$4", [to, path.relative(dataRoot(), target), projectId, filename]); return target; }
export async function locateTask(user: string, project: string, filename: string) { for (const status of TASK_STATUSES) { const file = taskPath(user, project, status, filename); try { const info = await stat(file); if (info.isFile() && !info.isSymbolicLink()) return { status, file }; } catch {} } return null; }
export async function reconcile(pool: Pick<Pool, "query">, project?: { id: string; user: string; slug: string }) { const projects = project ? [project] : (await pool.query("SELECT p.id,p.slug,u.slug user FROM projects p JOIN users u ON u.id=p.owner_id WHERE p.archived_at IS NULL")).rows; let synced = 0; for (const item of projects) for (const status of TASK_STATUSES) { const dir = path.join(projectRoot(item.user, item.slug), "tasks", status); for (const filename of await readdir(dir).catch(() => [])) { if (!/^\d{8}-\d{3}-task\.md$/.test(filename)) continue; const file = path.join(dir, filename); const content = await readFile(file, "utf8"); const { frontmatter } = parseMarkdown(content); await pool.query(`INSERT INTO tasks(project_id,filename,status,title,type,timeout_min,file_path,content_hash,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(project_id,filename) DO UPDATE SET status=EXCLUDED.status,title=EXCLUDED.title,file_path=EXCLUDED.file_path,content_hash=EXCLUDED.content_hash,updated_at=now()`, [item.id, filename, status, frontmatter.title, frontmatter.type, frontmatter.timeout_min ?? 20, path.relative(dataRoot(), file), contentHash(content), frontmatter.created_at]); synced++; } } return synced; }
