import test,{after,before}from"node:test";import assert from"node:assert/strict";import fs from"node:fs";import pg from"pg";import bcrypt from"bcryptjs";
const env=Object.fromEntries(fs.readFileSync(".env","utf8").split(/\r?\n/).filter(x=>x&&!x.startsWith("#")).map(line=>{const i=line.indexOf("=");return[line.slice(0,i),line.slice(i+1)]}));const base=process.env.APMS_BASE_URL??"http://127.0.0.1:9107";const slug=`docs-editor-${Date.now()}`;let cookie="",otherCookie="",projectId="";const client=new pg.Client({connectionString:env.DATABASE_URL});await client.connect();async function login(email=env.APMS_ADMIN_EMAIL,password=env.APMS_ADMIN_PASSWORD){const r=await fetch(`${base}/api/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})});assert.equal(r.status,200);return r.headers.get("set-cookie")}
before(async()=>{cookie=await login();const made=await fetch(`${base}/api/projects`,{method:"POST",headers:{cookie,"content-type":"application/json"},body:JSON.stringify({name:"Docs Editor Test",slug})});assert.equal(made.status,201);projectId=(await made.json()).id;const email=`other-${slug}@example.test`,password="test-password-123";await client.query("INSERT INTO users(email,password_hash,role)VALUES($1,$2,'user')",[email,await bcrypt.hash(password,4)]);otherCookie=await login(email,password)});after(async()=>{if(projectId)await client.query("UPDATE projects SET archived_at=now() WHERE id=$1",[projectId]);await client.query("DELETE FROM users WHERE email=$1",[`other-${slug}@example.test`]);await client.end()});
async function openGuide(){const response=await fetch(`${base}/api/projects/${slug}/docs/guide`,{headers:{cookie}});assert.equal(response.status,200);return{content:await response.text(),etag:response.headers.get("etag"),updatedAt:response.headers.get("x-updated-at")}}
async function saveGuide(content,etag){return fetch(`${base}/api/projects/${slug}/docs/guide`,{method:"PUT",headers:{cookie,"content-type":"application/json","if-match":etag},body:JSON.stringify({content})})}
test("GET ETag can be used immediately for PUT",async()=>{const opened=await openGuide();const saved=await saveGuide(`${opened.content}\nSaved by API test.\n`,opened.etag);assert.equal(saved.status,200);const body=await saved.json();assert.match(body.etag,/^"[a-f0-9]{64}"$/);assert.notEqual(body.etag,opened.etag);assert.notEqual(body.updated_at,opened.updatedAt)});
test("three consecutive PUTs use each successful response ETag",async()=>{let opened=await openGuide();for(let attempt=1;attempt<=3;attempt++){const saved=await saveGuide(`${opened.content}\nConsecutive save ${attempt}.\n`,opened.etag);assert.equal(saved.status,200,`save ${attempt}`);const body=await saved.json();opened={content:`${opened.content}\nConsecutive save ${attempt}.\n`,etag:body.etag,updatedAt:body.updated_at}}});
test("quoted, unquoted, and weak ETag forms are normalized",async()=>{let opened=await openGuide();for(const form of [etag=>etag,etag=>etag.slice(1,-1),etag=>`W/${etag}`]){const next=`${opened.content}\nETag normalization.\n`;const saved=await saveGuide(next,form(opened.etag));assert.equal(saved.status,200);const body=await saved.json();opened={content:next,etag:body.etag,updatedAt:body.updated_at}}});
test("external save makes an older ETag return 409",async()=>{const stale=await openGuide();const external=await saveGuide(`${stale.content}\nExternal tab save.\n`,stale.etag);assert.equal(external.status,200);const conflicted=await saveGuide(`${stale.content}\nStale tab save.\n`,stale.etag);assert.equal(conflicted.status,409);assert.equal((await conflicted.json()).error,"document_conflict")});
test("project sidebar is sticky and independently scrollable",()=>{const css=fs.readFileSync("src/app/globals.css","utf8");const rule=css.match(/\.project-sidebar\s*\{([^}]*)\}/)?.[1]||"";assert.match(rule,/position:\s*sticky/);assert.match(rule,/top:\s*60px/);assert.match(rule,/height:\s*calc\(100vh - 60px\)/);assert.match(rule,/overflow-y:\s*auto/)});
test("invalid setting frontmatter returns 400",async()=>{const opened=await fetch(`${base}/api/projects/${slug}/docs/setting`,{headers:{cookie}});const saved=await fetch(`${base}/api/projects/${slug}/docs/setting`,{method:"PUT",headers:{cookie,"content-type":"application/json","if-match":opened.headers.get("etag")},body:JSON.stringify({content:"---\nunknown_key: value\n---\n"})});assert.equal(saved.status,400);assert.equal((await saved.json()).error,"invalid_setting")});
test("another user receives 403",async()=>{const saved=await fetch(`${base}/api/projects/${slug}/docs/guide`,{method:"PUT",headers:{cookie:otherCookie,"content-type":"application/json","if-match":"\"anything\""},body:JSON.stringify({content:"forbidden"})});assert.equal(saved.status,403)});
test("relative image API rejects path traversal",async()=>{const escaped=await fetch(`${base}/api/projects/${slug}/files?path=${encodeURIComponent("docs/../../.env")}`,{headers:{cookie}});assert.equal(escaped.status,403);assert.equal((await escaped.json()).error,"path_escape")});
