import test,{after,before}from"node:test";import assert from"node:assert/strict";import fs from"node:fs";import pg from"pg";import bcrypt from"bcryptjs";
const env=Object.fromEntries(fs.readFileSync(".env","utf8").split(/\r?\n/).filter(x=>x&&!x.startsWith("#")).map(line=>{const i=line.indexOf("=");return[line.slice(0,i),line.slice(i+1)]})),base=process.env.DIRIGO_BASE_URL??"http://127.0.0.1:9107",pool=new pg.Pool({connectionString:env.DATABASE_URL});let cookie,otherCookie,ownerId,otherId,sessionId;
async function login(email,password){const r=await fetch(`${base}/api/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})});assert.equal(r.status,200);return r.headers.get("set-cookie")}
before(async()=>{cookie=await login(env.DIRIGO_ADMIN_EMAIL,env.DIRIGO_ADMIN_PASSWORD);ownerId=(await pool.query("SELECT id FROM users WHERE lower(email)=lower($1)",[env.DIRIGO_ADMIN_EMAIL])).rows[0].id;const email=`session-other-${Date.now()}@example.test`,password="session-test-password";otherId=(await pool.query("INSERT INTO users(email,password_hash,role) VALUES($1,$2,'user') RETURNING id",[email,await bcrypt.hash(password,4)])).rows[0].id;otherCookie=await login(email,password);const made=await fetch(`${base}/api/sessions`,{method:"POST",headers:{cookie,"content-type":"application/json"},body:"{}"});assert.equal(made.status,201);sessionId=(await made.json()).id});
after(async()=>{if(sessionId)await pool.query("DELETE FROM sessions WHERE id=$1",[sessionId]);if(otherId)await pool.query("DELETE FROM users WHERE id=$1",[otherId]);await pool.end()});
test("first user message title contract uses 40 characters without line breaks",async()=>{const source=fs.readFileSync(new URL("../src/app/api/chat/route.ts",import.meta.url),"utf8");assert.match(source,/regexp_replace/);assert.match(source,/regexp_replace\([^)]*\),40\)/);assert.match(source,/count\(\*\).*role='user'/)});
test("session can be renamed",async()=>{const r=await fetch(`${base}/api/sessions/${sessionId}`,{method:"PATCH",headers:{cookie,"content-type":"application/json"},body:JSON.stringify({title:"renamed session"})});assert.equal(r.status,200);assert.equal((await r.json()).title,"renamed session")});
test("another user receives 403 for rename and delete",async()=>{for(const method of["PATCH","DELETE"]){const r=await fetch(`${base}/api/sessions/${sessionId}`,{method,headers:{cookie:otherCookie,"content-type":"application/json"},body:method==="PATCH"?JSON.stringify({title:"forbidden"}):undefined});assert.equal(r.status,403)}});
test("deleting a session cascades to its messages",async()=>{await pool.query("INSERT INTO messages(session_id,role,content) VALUES($1,'user','cascade marker')",[sessionId]);const r=await fetch(`${base}/api/sessions/${sessionId}`,{method:"DELETE",headers:{cookie}});assert.equal(r.status,204);assert.equal(Number((await pool.query("SELECT count(*) n FROM messages WHERE session_id=$1",[sessionId])).rows[0].n),0);sessionId=null});
