import test from "node:test";import assert from"node:assert/strict";import{mkdtemp,readFile,writeFile}from"node:fs/promises";import{tmpdir}from"node:os";import path from"node:path";import{appendPlanning,docPath,initializeProject,nextTaskFilename,serializeMarkdown,parseMarkdown,createTaskFile,moveTask,reconcile,taskPath,writeDocument}from"../src/lib/storage/index.ts";
async function fixture(){const root=await mkdtemp(path.join(tmpdir(),"dirigo-storage-"));process.env.DIRIGO_DATA_ROOT=root;await initializeProject("test-user","test-project","Test Project");return root}
function fm(title="첫 작업"){return{title,project:"test-project",user:"test-user","pre-task":null,"next-task":null,type:"task",created_at:"2026-09-09T00:00:00.000Z",timeout_min:20}}
test("작업 파일명은 UTC 당일 최대 번호 + 1로 채번한다",async()=>{await fixture();assert.equal(await nextTaskFilename("test-user","test-project",new Date("2026-09-09T12:00:00Z")),"20260909-001-task.md");await writeFile(taskPath("test-user","test-project","done","20260909-004-task.md"),serializeMarkdown(fm(),"본문"));assert.equal(await nextTaskFilename("test-user","test-project",new Date("2026-09-09T12:00:00Z")),"20260909-005-task.md")});
test("frontmatter를 직렬화하고 손실 없이 파싱한다",()=>{const original={...fm(),custom:"보존"};const parsed=parseMarkdown(serializeMarkdown(original,"# 본문\n\n내용"));assert.deepEqual(parsed.frontmatter,original);assert.equal(parsed.body,"# 본문\n\n내용")});
test("상태 이동은 rename 후 DB status를 동기화한다",async()=>{await fixture();const file=await createTaskFile("test-user","test-project",fm(),"본문",new Date("2026-09-09T12:00:00Z"));const calls=[];await moveTask("test-user","test-project",file.filename,"pending","in-progress",{query:async(...args)=>calls.push(args)},"project-id");assert.equal(await readFile(taskPath("test-user","test-project","in-progress",file.filename),"utf8"),file.content);assert.equal(calls[0][1][0],"in-progress")});
test("reconcile은 파일 위치를 우선해 upsert한다",async()=>{await fixture();const file=await createTaskFile("test-user","test-project",fm("조정"),"본문",new Date("2026-09-09T12:00:00Z"));const calls=[];const synced=await reconcile({query:async(...args)=>{calls.push(args);return{rows:[]}}},{id:"project-id",user:"test-user",slug:"test-project"});assert.equal(synced,1);assert.match(calls[0][0],/ON CONFLICT/);assert.equal(calls[0][1][2],"pending");assert.equal(calls[0][1][1],file.filename)});
test("기획 append는 같은 날짜 절을 재사용하고 정규화 중복을 병합한다",async()=>{await fixture();await appendPlanning("test-user","test-project","2026-09-11",["담당자 필드를 추가한다."]);const result=await appendPlanning("test-user","test-project","2026-09-11",[" 담당자   필드를 추가한다 ","목록에 담당자를 표시한다"]);const content=await readFile(docPath("test-user","test-project","proposal"),"utf8");assert.equal((content.match(/## 기획 2026-09-11/g)||[]).length,1);assert.equal((content.match(/담당자 필드를 추가한다/g)||[]).length,1);assert.deepEqual(result.duplicates,["담당자   필드를 추가한다"]);assert.match(content,/목록에 담당자를 표시한다/)});
test("기획 append는 모델이 보낸 선행 bullet 표식을 한 번만 기록한다",async()=>{await fixture();await appendPlanning("test-user","test-project","2026-09-11",["- 목록 표시","1) 상세 편집"]);const content=await readFile(docPath("test-user","test-project","proposal"),"utf8");assert.match(content,/\n- 목록 표시\n- 상세 편집\n/);assert.doesNotMatch(content,/\n- - /)});
test("동시 기획 append는 모든 항목을 보존한다",async()=>{await fixture();await Promise.all([appendPlanning("test-user","test-project","2026-09-11",["목록 표시"]),appendPlanning("test-user","test-project","2026-09-11",["상세 편집"])]);const content=await readFile(docPath("test-user","test-project","proposal"),"utf8");assert.match(content,/목록 표시/);assert.match(content,/상세 편집/)});
test("해시 충돌은 한 번 재시도하고 이후 성공한다",async()=>{await fixture();let injected=false;const result=await appendPlanning("test-user","test-project","2026-09-11",["충돌 후 기록"],async()=>{if(!injected){injected=true;await writeDocument("test-user","test-project","proposal","# 외부 변경\n")}});assert.deepEqual(result.added,["충돌 후 기록"]);assert.match(await readFile(docPath("test-user","test-project","proposal"),"utf8"),/# 외부 변경[\s\S]*충돌 후 기록/)});
test("시크릿이 포함된 기획 항목은 문서를 변경하지 않고 거부한다",async()=>{await fixture();const file=docPath("test-user","test-project","proposal"),before=await readFile(file,"utf8");await assert.rejects(()=>appendPlanning("test-user","test-project","2026-09-11",["password=do-not-store"]),/planning_secret_rejected/);assert.equal(await readFile(file,"utf8"),before)});
