import { mkdir, open, readFile } from "node:fs/promises";
import path from "node:path";
import { CONFIG_TEMPLATE } from "../lib/config/template";
import { configPaths, getConfig, maskSecrets, validateYaml } from "../lib/config/loader";
import { diffConfig } from "../lib/config/diff";
import { applyConfig, ConfigConflictError, readRawConfig } from "../lib/config/writer";

function flags(args: string[]) { const take = (name: string) => { const i = args.indexOf(name); if (i < 0) return undefined; const value = args[i + 1]; args.splice(i, value && !value.startsWith("--") ? 2 : 1); return value ?? "true"; }; return { json: take("--json") != null, project: take("--project"), dryRun: take("--dry-run") != null, local: take("--local") != null }; }
function print(value: unknown, json: boolean) { if (json) console.log(JSON.stringify(value, null, 2)); else if (typeof value === "string") console.log(value); else console.log(JSON.stringify(value, null, 2)); }
function at(value: any, key?: string) { return key?.split(".").reduce((node, part) => node?.[part], value) ?? value; }
async function input(file: string | undefined, current: () => Promise<string>) { return file ? readFile(path.resolve(file), "utf8") : current(); }
async function server(command: string, args: string[], options: ReturnType<typeof flags>) { const base = process.env.DIRIGO_URL; if (!base) throw new Error("DIRIGO_URL is required for server mode"); const project = options.project ? `?project=${encodeURIComponent(options.project)}` : ""; const endpoint = command === "get" || command === "apply" ? `/api/config${project}` : command === "init" ? "" : `/api/config/${command}${project}`; if (command === "init") throw new Error("init is available in local mode only"); const method = command === "get" ? "GET" : command === "apply" ? "PUT" : "POST"; const body = method === "GET" ? undefined : await input(args[0], async () => ""); const response = await fetch(new URL(endpoint, base), { method, body, headers: { ...(body ? { "content-type": "application/yaml" } : {}), ...(process.env.DIRIGO_TOKEN ? { authorization: `Bearer ${process.env.DIRIGO_TOKEN}` } : {}) } }); const result = await response.json(); print(result, options.json); return response.status === 409 ? 2 : response.ok ? 0 : 1; }
export async function main(argv = process.argv.slice(2)) { const args = [...argv]; if (args.shift() !== "config") throw new Error("usage: dirigo config init|get|validate|diff|apply"); const command = args.shift() ?? ""; const options = flags(args); if (!options.local && args.includes("--server")) { args.splice(args.indexOf("--server"), 1); return server(command, args, options); }
  if (command === "init") { const file = options.project ? configPaths(options.project).project! : configPaths().global; await mkdir(path.dirname(file), { recursive: true }); try { const handle = await open(file, "wx", 0o600); await handle.writeFile(options.project ? "# Project-scoped Dirigo overrides\n{}\n" : CONFIG_TEMPLATE); await handle.close(); print({ created: file }, options.json); return 0; } catch (error) { if ((error as NodeJS.ErrnoException).code === "EEXIST") { print({ error: "config_exists", file }, options.json); return 1; } throw error; } }
  if (command === "get") { const loaded = getConfig({ project: options.project }); const key = args[0]; print(key ? { key, value: maskSecrets(at(loaded.config, key)), source: loaded.sources[key] } : { config: maskSecrets(loaded.config), sources: loaded.sources, warnings: loaded.warnings, hash: loaded.hash }, options.json); return 0; }
  const yaml = await input(args[0], () => readRawConfig({ project: options.project })); const validation = validateYaml(yaml, { project: Boolean(options.project), env: process.env }); if (command === "validate") { print(validation, options.json); return validation.valid ? 0 : 1; } if (!validation.valid) { print(validation, options.json); return 1; }
  if (command === "diff" || options.dryRun) { print({ valid: true, changes: diffConfig(yaml, { project: options.project }), warnings: validation.warnings }, options.json); return 0; }
  if (command === "apply") { try { const result = await applyConfig(yaml, { project: options.project, ifMatch: getConfig({ project: options.project }).hash, actor: "cli" }); print({ applied: true, hash: result.hash, changes: result.changes, warnings: result.warnings }, options.json); return 0; } catch (error) { if (error instanceof ConfigConflictError) { print({ error: "config_conflict", current_hash: error.currentHash }, options.json); return 2; } throw error; } }
  throw new Error("usage: dirigo config init|get|validate|diff|apply");
}
main().then((code) => { process.exitCode = code; }).catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; });
