import { ownedProject, requestJson, jsonError } from "@/lib/api";
import { DOC_KINDS, documentMetadata, writeDocument, type DocKind } from "@/lib/storage/index";

const EDITABLE_KINDS: readonly DocKind[] = ["guide", "next", "setting"];
const SETTING_TYPES: Record<string, "string" | "integer" | "string[]"> = {
  repo:"string",branch:"string",push_policy:"string",verify_cmd:"string",workdir:"string",
  workspace:"string",remote_host:"string",remote_port:"integer",remote_user:"string",
  remote_os:"string",remote_workdir:"string",max_concurrent:"integer",guides:"string[]",secrets:"string[]",
};

function parseScalar(raw:string){const value=raw.trim();if(!value)return "";if(/^\d+$/.test(value))return Number(value);if(value.startsWith("[")&&value.endsWith("]")){return value.slice(1,-1).split(",").map(v=>v.trim().replace(/^['"]|['"]$/g,"")).filter(Boolean)}return value.replace(/^['"]|['"]$/g,"");}
function validateSetting(content:string){const match=content.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/);if(!match)return "setting 문서는 YAML frontmatter(---)가 필요합니다.";const values:Record<string,unknown>={};for(const line of match[1].split(/\r?\n/)){if(!line.trim()||line.trimStart().startsWith("#"))continue;const field=line.match(/^([a-z_]+):\s*(.*)$/);if(!field)return `setting frontmatter 형식이 올바르지 않습니다: ${line}`;const [,key,raw]=field;if(!(key in SETTING_TYPES))return `허용되지 않은 setting 키입니다: ${key}`;if(key in values)return `중복된 setting 키입니다: ${key}`;values[key]=parseScalar(raw)}for(const [key,value] of Object.entries(values)){const expected=SETTING_TYPES[key];if(expected==="string"&&typeof value!=="string")return `${key}는 문자열이어야 합니다.`;if(expected==="integer"&&!Number.isInteger(value))return `${key}는 정수여야 합니다.`;if(expected==="string[]"&&(!Array.isArray(value)||value.some(v=>typeof v!=="string")))return `${key}는 문자열 이름 배열이어야 합니다.`}if(values.workspace&&!['local','remote'].includes(String(values.workspace)))return "workspace는 local 또는 remote여야 합니다.";if(values.secrets&&Array.isArray(values.secrets)&&values.secrets.some(v=>!/[A-Za-z0-9_.-]+/.test(String(v))))return "secrets에는 값이 아닌 비밀 이름만 입력할 수 있습니다.";return null;}

export async function GET(_: Request, { params }: RouteContext<"/api/projects/[slug]/docs/[kind]">) { const {slug,kind}=await params; const own=await ownedProject(slug); if("error" in own)return own.error; if(!DOC_KINDS.includes(kind as DocKind))return jsonError("invalid_kind",404); const doc=await documentMetadata(own.user.storageSlug,slug,kind as DocKind); return new Response(doc.content,{headers:{"Content-Type":"text/markdown; charset=utf-8",ETag:doc.etag,"X-Updated-At":doc.updatedAt}}); }
export async function PUT(request: Request, { params }: RouteContext<"/api/projects/[slug]/docs/[kind]">) { const {slug,kind}=await params; const own=await ownedProject(slug); if("error" in own)return own.error; if(!EDITABLE_KINDS.includes(kind as DocKind))return jsonError("document_not_editable",403); const type=request.headers.get("content-type")||""; const content=type.includes("application/json")?(await requestJson<{content?:string}>(request))?.content:await request.text(); if(typeof content!=="string")return jsonError("content_required");const current=await documentMetadata(own.user.storageSlug,slug,kind as DocKind);const ifMatch=request.headers.get("if-match");if(!ifMatch)return Response.json({error:"if_match_required",message:"문서를 다시 불러온 뒤 저장해 주세요."},{status:428});if(ifMatch!==current.etag)return Response.json({error:"document_conflict",message:"다른 곳에서 문서가 수정되었습니다.",updated_at:current.updatedAt,etag:current.etag},{status:409});if(kind==="setting"){const error=validateSetting(content);if(error)return Response.json({error:"invalid_setting",message:error},{status:400})}await writeDocument(own.user.storageSlug,slug,kind as DocKind,content);const saved=await documentMetadata(own.user.storageSlug,slug,kind as DocKind);return Response.json({ok:true,updated_at:saved.updatedAt,etag:saved.etag}); }
