import path from "node:path"; import { db } from "@/lib/db"; import { ownedProject, requestJson, jsonError } from "@/lib/api"; import { createTaskFile, contentHash, dataRoot, type Frontmatter } from "@/lib/storage/index";

export function pagination(searchParams: URLSearchParams) {
  const requestedLimit = Number(searchParams.get("limit"));
  const requestedOffset = Number(searchParams.get("offset"));
  const limit = Number.isInteger(requestedLimit) && requestedLimit > 0 ? Math.min(requestedLimit, 50) : 5;
  const offset = Number.isInteger(requestedOffset) && requestedOffset >= 0 ? requestedOffset : 0;
  return { limit, offset };
}

export async function GET(request: Request,{params}:RouteContext<"/api/projects/[slug]/tasks">){const{slug}=await params;const own=await ownedProject(slug);if("error"in own)return own.error;const searchParams=new URL(request.url).searchParams;const raw=searchParams.get("status");const statuses=raw?.split(",").filter(Boolean);const{limit,offset}=pagination(searchParams);const filtered=statuses?.length;const where=filtered?"WHERE t.project_id=$1 AND t.status::text=ANY($2::text[])":"WHERE t.project_id=$1";const values=filtered?[own.project.id,statuses,limit,offset]:[own.project.id,limit,offset];const limitParameter=filtered?"$3":"$2";const offsetParameter=filtered?"$4":"$3";const result=await db.query(`SELECT t.*,r.pid,r.started_at run_started_at,coalesce(extract(epoch FROM now()-r.started_at)::int,0) elapsed_seconds,count(*) OVER()::int total_count FROM tasks t LEFT JOIN LATERAL(SELECT pid,started_at FROM task_runs WHERE task_id=t.id AND status='running' ORDER BY attempt DESC LIMIT 1)r ON true ${where} ORDER BY t.priority DESC,t.created_at DESC LIMIT ${limitParameter} OFFSET ${offsetParameter}`,values);let total=result.rows[0]?.total_count??0;if(!result.rows.length&&offset>0){const counted=await db.query(`SELECT count(*)::int total FROM tasks t ${where}`,filtered?[own.project.id,statuses]:[own.project.id]);total=counted.rows[0].total;}const items=result.rows.map((row)=>{const item={...row};delete item.total_count;return item;});return Response.json({items,total,limit,offset});}
export async function POST(request:Request,{params}:RouteContext<"/api/projects/[slug]/tasks">){const{slug}=await params;const own=await ownedProject(slug);if("error"in own)return own.error;const body=await requestJson<{title?:string;body?:string;"pre-task"?:string|null;"next-task"?:string|null;timeout_min?:number}>(request);if(!body?.title?.trim()||body.title.trim().length>120)return jsonError("invalid_title");const timeout=body.timeout_min??20;if(!Number.isInteger(timeout)||timeout<1||timeout>1440)return jsonError("invalid_timeout");for(const dependency of [body["pre-task"],body["next-task"]])if(dependency){const found=await db.query("SELECT 1 FROM tasks WHERE project_id=$1 AND filename=$2",[own.project.id,dependency]);if(!found.rowCount)return jsonError("invalid_dependency",422);}const createdAt=new Date().toISOString();const frontmatter:Frontmatter={title:body.title.trim(),project:slug,user:own.user.storageSlug,"pre-task":body["pre-task"]||null,"next-task":body["next-task"]||null,type:"task",created_at:createdAt,timeout_min:timeout};try{const file=await createTaskFile(own.user.storageSlug,slug,frontmatter,body.body||`# ${body.title.trim()}`);const result=await db.query("INSERT INTO tasks(project_id,filename,status,title,type,timeout_min,file_path,content_hash,created_at) VALUES($1,$2,'pending',$3,'task',$4,$5,$6,$7) RETURNING *",[own.project.id,file.filename,frontmatter.title,timeout,path.relative(dataRoot(),file.path),contentHash(file.content),createdAt]);return Response.json(result.rows[0],{status:201});}catch(error){if((error as{code?:string}).code==="23505")return jsonError("task_conflict",409);throw error;}}
