"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
type Project={id:string;name:string;slug:string;updated_at:string;task_counts:Record<string,number>};
type WorkerStatus={running:unknown[];limit:number;scheduler:{healthy:boolean}};
export default function DashboardClient(){
 const[items,setItems]=useState<Project[]>([]);const[workers,setWorkers]=useState<WorkerStatus|null>(null);const[mode,setMode]=useState("card");const[modal,setModal]=useState(false);const[slug,setSlug]=useState("");
 async function load(){const r=await fetch("/api/projects");if(r.ok)setItems((await r.json()).items)}
 useEffect(()=>{void load();const poll=()=>fetch("/api/workers/status",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(setWorkers).catch(()=>setWorkers(null));void poll();const timer=setInterval(poll,10000);return()=>clearInterval(timer)},[]);
 function switchMode(value:string){setMode(value);localStorage.setItem("apms-view",value)}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const r=await fetch("/api/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:form.get("name"),slug})});if(r.ok){setModal(false);setSlug("");await load()}else alert((await r.json()).error)}
 return <main className="page"><div className="worker-strip"><span>워커 {workers?.running.length??0}/{workers?.limit??20}</span><span className={workers?.scheduler.healthy?"healthy":"stopped"}>스케줄러 {workers?.scheduler.healthy?"정상":"중단"}</span></div><div className="page-head"><div><p className="eyebrow">PROJECTS</p><h1>내 프로젝트</h1></div><div className="head-actions"><div className="segmented"><button className={mode==="card"?"active":""} onClick={()=>switchMode("card")}>카드</button><button className={mode==="list"?"active":""} onClick={()=>switchMode("list")}>목록</button></div><button className="primary" onClick={()=>setModal(true)}>새 프로젝트</button></div></div><div className={`projects ${mode}`}>{items.map(p=><Link href={`/p/${p.slug}`} className="project-item" key={p.id}><div><h2>{p.name}</h2><code>{p.slug}</code></div><div className="counts"><span>대기 {p.task_counts.pending||0}</span><span>진행 {p.task_counts.in_progress||0}</span><span>완료 {p.task_counts.done||0}</span><span className={(p.task_counts.failed||0)>0?"danger":""}>실패 {p.task_counts.failed||0}</span></div><time>갱신 {new Date(p.updated_at).toLocaleString("ko-KR")}</time></Link>)}</div>{!items.length&&<div className="empty">첫 프로젝트를 만들어 작업을 시작하세요.</div>}{modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(false)}><form className="modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><h2>새 프로젝트</h2><label>이름<input name="name" required autoFocus onChange={e=>setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""))}/></label><label>Slug<input name="slug" required value={slug} onChange={e=>setSlug(e.target.value)}/></label><div className="modal-actions"><button type="button" onClick={()=>setModal(false)}>취소</button><button className="primary">생성</button></div></form></div>}</main>
}
