import { createHash } from "node:crypto";
import { readFileSync, statSync } from "node:fs";
import path from "node:path";
import { parse } from "yaml";
import { configSchema, defaultConfig, formatZodIssues, type ConfigIssue, type ConfigSource, type DirigoConfig } from "./schema";

export type LoadedConfig = { config: DirigoConfig; sources: Record<string, ConfigSource>; warnings: ConfigIssue[]; hash: string; raw: string; file: string };
const ENV_MAP: Record<string, { path: string; parse?: (value: string) => unknown }> = {
  DIRIGO_BASE_URL: { path: "server.base_url" }, DIRIGO_SESSION_TTL_HOURS: { path: "server.session_ttl_hours", parse: Number }, DIRIGO_REMEMBER_TTL_DAYS: { path: "server.remember_ttl_days", parse: Number },
  DIRIGO_SCHEDULER_INTERVAL_MS: { path: "worker.scheduler_interval_ms", parse: Number }, DIRIGO_MAX_WORKERS: { path: "worker.max_workers", parse: Number }, DIRIGO_WORKER_RUNNER: { path: "worker.runner" }, DIRIGO_OPENCODE_BIN: { path: "worker.opencode_bin" }, DIRIGO_OPENCODE_PATH: { path: "worker.opencode_path" }, DIRIGO_WORKDIR_ALLOWLIST: { path: "worker.workdir_allowlist", parse: (v) => v.split(path.delimiter).filter(Boolean) },
  DIRIGO_SEARXNG_URL: { path: "search.searxng_url" }, DIRIGO_SEARCH_MAX_RESULTS: { path: "search.max_results", parse: Number }, DIRIGO_SEARCH_RATE_LIMIT_PER_MIN: { path: "search.rate_limit_per_min", parse: Number },
  DIRIGO_FETCH_TIMEOUT_MS: { path: "fetch.timeout_ms", parse: Number }, DIRIGO_FETCH_MAX_BYTES: { path: "fetch.max_bytes", parse: Number }, DIRIGO_FETCH_MAX_CHARS: { path: "fetch.max_chars", parse: Number }, DIRIGO_SMTP_URL: { path: "notifications.smtp_url" }, DIRIGO_SMTP_FROM: { path: "notifications.smtp_from" },
};
export { ENV_MAP };

function clone<T>(value: T): T { return structuredClone(value); }
function leaves(value: unknown, prefix = ""): string[] { if (Array.isArray(value)) return value.flatMap((item, i) => leaves(item, `${prefix}[${i}]`)); if (value && typeof value === "object") return Object.entries(value).flatMap(([key, item]) => leaves(item, prefix ? `${prefix}.${key}` : key)); return prefix ? [prefix] : []; }
function merge(target: Record<string, any>, source: Record<string, any>, label: ConfigSource, sources: Record<string, ConfigSource>, prefix = "") { for (const [key, value] of Object.entries(source)) { const full = prefix ? `${prefix}.${key}` : key; if (value && typeof value === "object" && !Array.isArray(value)) { target[key] ??= {}; merge(target[key], value, label, sources, full); } else { target[key] = clone(value); for (const leaf of leaves(value, full)) sources[leaf] = label; if (!leaves(value, full).length) sources[full] = label; } } }
function setPath(target: any, dotted: string, value: unknown) { const keys = dotted.split("."); let node = target; for (const key of keys.slice(0, -1)) node = node[key]; node[keys.at(-1)!] = value; }
function read(file: string) { try { return readFileSync(file, "utf8"); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return ""; throw error; } }
function parseYaml(raw: string, file: string): Record<string, any> { if (!raw.trim()) return {}; const value = parse(raw); if (value == null) return {}; if (typeof value !== "object" || Array.isArray(value)) throw new ConfigValidationError([{ path: file, message: "root must be a mapping" }]); return value; }
export class ConfigValidationError extends Error { constructor(public issues: ConfigIssue[]) { super(issues.map((i) => `${i.path}: ${i.message}`).join("\n")); } }
export function configPaths(project?: string, root = process.env.DIRIGO_DATA_ROOT || "./data") { if (project && !/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])$/.test(project)) throw new Error("invalid project slug"); const base = path.resolve(root); return { global: path.join(base, "config", "dirigo.yaml"), project: project ? path.join(base, "projects", project, "project.yaml") : undefined }; }
export function validateYaml(raw: string, options: { project?: boolean; env?: NodeJS.ProcessEnv } = {}) { const warnings: ConfigIssue[] = []; let value: Record<string, any>; try { value = parseYaml(raw, "yaml"); } catch (error) { return { valid: false, errors: error instanceof ConfigValidationError ? error.issues : [{ path: "yaml", message: String(error) }], warnings }; }
  if (options.project) for (const key of Object.keys(value)) if (["server", "worker", "cli"].includes(key)) return { valid: false, errors: [{ path: key, message: "not allowed in project config" }], warnings };
  const merged = clone(defaultConfig); merge(merged as any, value, options.project ? "project" : "yaml", {});
  const result = configSchema.safeParse(merged); const errors = result.success ? [] : formatZodIssues(result.error);
  walk(value, "", (key, item) => { if (/(?:api_key|password|token)$/.test(key) && typeof item === "string" && item.length >= 8 && !item.includes("${")) errors.push({ path: key, message: "plaintext secret is forbidden; use ${env:NAME}" }); if (typeof item === "string") { const match = item.match(/^\$\{env:([A-Z_][A-Z0-9_]*)\}$/); if (match && !options.env?.[match[1]]) warnings.push({ path: key, message: `environment variable ${match[1]} is not set` }); } });
  const uniqueErrors = errors.filter((item, index) => errors.findIndex((candidate) => candidate.path === item.path && candidate.message === item.message) === index);
  return { valid: uniqueErrors.length === 0, errors: uniqueErrors, warnings, value };
}
function walk(value: unknown, prefix: string, visit: (path: string, value: unknown) => void) { if (Array.isArray(value)) value.forEach((item, i) => walk(item, `${prefix}[${i}]`, visit)); else if (value && typeof value === "object") Object.entries(value).forEach(([key, item]) => walk(item, prefix ? `${prefix}.${key}` : key, visit)); else visit(prefix, value); }
function resolveEnv(value: any, env: NodeJS.ProcessEnv, warnings: ConfigIssue[], prefix = ""): any { if (Array.isArray(value)) return value.map((item, i) => resolveEnv(item, env, warnings, `${prefix}[${i}]`)); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, resolveEnv(item, env, warnings, prefix ? `${prefix}.${key}` : key)])); if (typeof value === "string") { const match = value.match(/^\$\{env:([A-Z_][A-Z0-9_]*)\}$/); if (match) { if (env[match[1]] == null) { warnings.push({ path: prefix, message: `environment variable ${match[1]} is not set` }); return ""; } return env[match[1]]; } } return value; }
export function getConfig(options: { project?: string; root?: string; env?: NodeJS.ProcessEnv } = {}): LoadedConfig { const env = options.env ?? process.env; const files = configPaths(options.project, options.root); const raw = read(files.global); const projectRaw = files.project ? read(files.project) : ""; const globalCheck = validateYaml(raw, { env }); const projectCheck = validateYaml(projectRaw, { project: true, env }); const issues = [...globalCheck.errors, ...projectCheck.errors]; if (issues.length) throw new ConfigValidationError(issues);
  const config = clone(defaultConfig); const sources: Record<string, ConfigSource> = {}; leaves(config).forEach((key) => sources[key] = "default"); merge(config as any, parseYaml(raw, files.global), "yaml", sources); if (files.project) merge(config as any, parseYaml(projectRaw, files.project), "project", sources); for (const [name, mapping] of Object.entries(ENV_MAP)) if (env[name] != null && env[name] !== "") { setPath(config, mapping.path, mapping.parse ? mapping.parse(env[name]!) : env[name]); sources[mapping.path] = "env"; }
  const parsed = configSchema.safeParse(config); if (!parsed.success) throw new ConfigValidationError(formatZodIssues(parsed.error)); const warnings = [...globalCheck.warnings, ...projectCheck.warnings]; const resolved = resolveEnv(parsed.data, env, warnings); return { config: resolved, sources, warnings, hash: createHash("sha256").update(options.project ? projectRaw : raw).digest("hex"), raw: options.project ? projectRaw : raw, file: options.project ? files.project! : files.global };
}
export function invalidateConfigCache() { /* stateless loader: next request/tick always sees disk */ }
export function configMtime(file: string) { try { return statSync(file).mtimeMs; } catch { return 0; } }
export function maskSecrets(value: any, prefix = ""): any { if (Array.isArray(value)) return value.map((item, i) => maskSecrets(item, `${prefix}[${i}]`)); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, /(?:api_key|password|token)$/.test(key) ? "***" : maskSecrets(item, prefix ? `${prefix}.${key}` : key)])); return value; }
