"use client";
import{useEffect,useMemo,useState}from"react";
type Section="in-progress"|"pending"|"done"|"failed"|"reports";type Me={email:string;slug:string;role:string;display_name:string|null;created_at:string;preferences:{language:"ko"|"en";chat_panel_width:number;task_default_sections:Section[];email_notifications:boolean;notification_email:string}};
const options:[Section,string][]=[["in-progress","진행"],["pending","대기"],["done","완료"],["failed","실패"],["reports","리포트"]],stable=(v:unknown)=>JSON.stringify(v);
export function isSettingsDirty(a:Me|null,b:Me|null){return Boolean(a&&b&&stable({display_name:a.display_name,preferences:a.preferences})!==stable({display_name:b.display_name,preferences:b.preferences}))}
export default function SettingsClient(){const[initial,setInitial]=useState<Me|null>(null),[me,setMe]=useState<Me|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[toast,setToast]=useState("");const[password,setPassword]=useState({current_password:"",new_password:"",confirm_password:""}),[passwordError,setPasswordError]=useState<{field?:string;message:string}|null>(null),[passwordSaving,setPasswordSaving]=useState(false);const dirty=useMemo(()=>isSettingsDirty(initial,me),[initial,me]);
useEffect(()=>{fetch("/api/me",{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>{setInitial(d);setMe(d)}).catch(()=>setToast("설정을 불러오지 못했습니다.")).finally(()=>setLoading(false))},[]);
useEffect(()=>{const unload=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}},click=(e:MouseEvent)=>{if(!dirty)return;const link=(e.target as Element).closest("a[href]") as HTMLAnchorElement|null;if(link&&link.origin===location.origin&&link.pathname!==location.pathname&&!confirm("저장하지 않은 변경사항이 있습니다. 페이지를 떠나시겠습니까?"))e.preventDefault()};window.addEventListener("beforeunload",unload);document.addEventListener("click",click,true);return()=>{window.removeEventListener("beforeunload",unload);document.removeEventListener("click",click,true)}},[dirty]);
if(loading)return <main className="page settings-page"><p>불러오는 중…</p></main>;if(!me)return <main className="page settings-page"><p>설정을 불러오지 못했습니다.</p></main>;const prefs=(patch:Partial<Me["preferences"]>)=>setMe({...me,preferences:{...me.preferences,...patch}});
async function save(){setSaving(true);const r=await fetch("/api/me",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({display_name:me!.display_name,preferences:me!.preferences})}),body=await r.json().catch(()=>({}));setSaving(false);if(!r.ok){setToast(body.error||"저장하지 못했습니다.");return}setMe(body);setInitial(body);localStorage.setItem("apms.chat.panel.width",String(body.preferences.chat_panel_width));localStorage.setItem("apms.project.chat.width",String(body.preferences.chat_panel_width));localStorage.setItem("apms.tasks.default.sections",JSON.stringify(body.preferences.task_default_sections));window.dispatchEvent(new CustomEvent("dirigo:display-name",{detail:body.display_name}));setToast("저장됨");setTimeout(()=>setToast(""),2500)}
async function changePassword(){setPasswordError(null);if(password.new_password!==password.confirm_password){setPasswordError({field:"confirm_password",message:"새 비밀번호 확인이 일치하지 않습니다."});return}setPasswordSaving(true);const r=await fetch("/api/me/password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(password)}),body=await r.json().catch(()=>({}));setPasswordSaving(false);if(!r.ok){setPasswordError({field:body.field,message:body.error||"비밀번호를 변경하지 못했습니다."});return}setPassword({current_password:"",new_password:"",confirm_password:""});setToast("비밀번호가 변경되었습니다.");setTimeout(()=>setToast(""),2500)}
return <main className="page settings-page"><p className="eyebrow">ACCOUNT</p><h1>개인설정</h1><section className="settings-card"><h2>계정 정보</h2><div className="settings-grid"><span>이메일</span><strong>{me.email}</strong><span>slug</span><strong>{me.slug}</strong><span>역할</span><strong>{me.role}</strong><span>가입일</span><strong>{new Date(me.created_at).toLocaleDateString("ko-KR")}</strong></div><label>표시 이름<input value={me.display_name||""} maxLength={40} onChange={e=>setMe({...me,display_name:e.target.value})}/><small>1~40자</small></label></section>
<section className="settings-card"><h2>비밀번호 변경</h2>{(["current_password","new_password","confirm_password"] as const).map((field,i)=><label key={field}>{["현재 비밀번호","새 비밀번호","새 비밀번호 확인"][i]}<input type="password" autoComplete={i?"new-password":"current-password"} value={password[field]} onChange={e=>setPassword({...password,[field]:e.target.value})}/>{passwordError?.field===field&&<span className="field-error">{passwordError.message}</span>}</label>)}{passwordError&&!passwordError.field&&<p className="field-error">{passwordError.message}</p>}<button className="primary settings-button" disabled={passwordSaving||!password.current_password||password.new_password.length<8||!password.confirm_password} onClick={changePassword}>{passwordSaving?"변경 중…":"비밀번호 변경"}</button></section>
<section className="settings-card"><h2>환경설정</h2><label>UI 언어<select value={me.preferences.language} onChange={e=>prefs({language:e.target.value as"ko"|"en"})}><option value="ko">한국어</option><option value="en">English</option></select></label><label>채팅 패널 기본 폭 (px)<input type="number" min="320" max="720" value={me.preferences.chat_panel_width} onChange={e=>prefs({chat_panel_width:Number(e.target.value)})}/></label><fieldset><legend>작업 탭 기본 펼침 섹션</legend>{options.map(([key,label])=><label className="check-row" key={key}><input type="checkbox" checked={me.preferences.task_default_sections.includes(key)} onChange={e=>prefs({task_default_sections:e.target.checked?[...me.preferences.task_default_sections,key]:me.preferences.task_default_sections.filter(x=>x!==key)})}/>{label}</label>)}</fieldset></section>
<section className="settings-card"><h2>알림</h2><label className="check-row"><input type="checkbox" checked={me.preferences.email_notifications} onChange={e=>prefs({email_notifications:e.target.checked})}/>작업 완료 이메일 알림</label><label>수신 이메일<input type="email" value={me.preferences.notification_email} disabled={!me.preferences.email_notifications} onChange={e=>prefs({notification_email:e.target.value})}/></label></section>
<div className="settings-savebar"><span className={dirty?"dirty-badge":""}>{dirty?"저장되지 않은 변경":"변경사항 없음"}</span><div><button disabled={!dirty||saving} onClick={()=>setMe(initial)}>취소</button><button className="primary" disabled={!dirty||saving} onClick={save}>{saving?"저장 중…":"저장"}</button></div></div>{toast&&<div className="toast" role="status">{toast}</div>}</main>}
